site_name: CBWS
theme:
  name: material
  features:
    - tabs
    #- instant
nav:
  - Home: index.md
  - Services:
    - Colocation: '!include ./colocation/mkdocs.yml'
    - Identity & Access Management: '!include ./iam/mkdocs.yml'
    - Projects: '!include ./projects/mkdocs.yml'
    - Virtual Private Clouds: '!include ./vpc/mkdocs.yml'
    - Public Network: '!include ./network/mkdocs.yml'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - content.code.
  - navigation.sections
  - navigation.path
  - navigation.top
  - search.suggest

plugins:
  - monorepo
  - search
  - glightbox

copyright: >
  Copyright &copy; 2025 CBWS B.V.
