site_name: CBWS
theme:
  name: material
  features:
    - tabs
    #- instant
nav:
  - Home: index.md
  - Services:
    - Identity & Access Management: '!include ./iam/mkdocs.yml'
    - Projects: '!include ./projects/mkdocs.yml'
    - Virtual Private Clouds: '!include ./vpc/mkdocs.yml'
    - Public Network: '!include ./network/mkdocs.yml'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tabbed
  - pymdownx.superfences

plugins:
  - monorepo
