site_name: iam
theme:
  name: material

nav:
  - Guides:
      - Getting started: "getting-started.md"
#  - Reference:
#      - Permissions/roles: "reference/permissions.md"
#      - Golang: "golang.md"
#      - PHP: "php.md"
#      - Protobuf: "reference/protobuf.md"
